networks:
  default:
    name: lusha_net

services:
  myenv:
    image: lusha/pydev_env
    stdin_open: true
    tty: true
    container_name: lusha_pydev_env
    user: "${UID}:${GID}"
    ports: # HOST:CONTAINER
      - "10882:8888"
    volumes:
      - /home/lusha/datasets/private:/app/data/datasets/private
      - /home/lusha/datasets/shared:/app/data/datasets/shared
      - /home/lusha/storage/:/app/home
    deploy:
      resources:
        reservations:
          devices:
            - capabilities: [gpu]
              device_ids: []
    cpuset: "12-23"
    networks:
      - default