networks:
  default:
    name: lusha_net

services:
  env_container:
    image: lusha/pydev
    container_name: lusha_pydev_env
    user: "1142:1142"
    stdin_open: true  # same as -i
    tty: true         # same as -t
    command: /bin/bash
    ports: # HOST:CONTAINER
      - "10882:8888"
    volumes:
      - /home/lusha/storage:/home/lusha
      - /multiverse/datasets/lusha:/home/lusha/star_code/data/datasets
      - /multiverse/datasets/shared/action-genome:/home/lusha/star_code/data/datasets/action-genome
      - /multiverse/datasets/shared/STAR:/home/lusha/star_code/data/datasets/STAR
    deploy:
      resources:
        reservations:
          devices:
            - capabilities: [gpu]
              device_ids: ["7"]
    cpuset: "36-39"
    networks:
      - default