version: '3'

networks:
  default:
    name: ollama-network
    external: true

services:
  ollama:
    image: lusha/ollama
    environment:
      - OLLAMA_LOG=debug
      - OLLAMA_DEBUG=1
    user: "${UID}:${GID}"
    ports:
      - "11434:11434"
    volumes:
      - /home/lusha/storage/ollama/ollama_models:/.ollama
      - /home/lusha/storage/ollama/logs:/.ollama/logs
    container_name: lusha_ollama
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              device_ids: ["_"]
              capabilities: [gpu]
    cpuset: "0-3"
    restart: "no"
    networks:
      - default
