version: '3'
networks:
  default:
    name: lusha_network

services:
  ollama:
    image: lusha/ollama
    environment:
      - OLLAMA_LOG=debug
      - OLLAMA_DEBUG=1
    user: "${UID-1142}:${GID-1142}"
    ports:  
      - "11434:11434"
    volumes:
      - /home/lusha/storage/ollama/ollama_models:/.ollama 
    container_name: lusha_ollama
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              device_ids: ["4"]
              capabilities: [gpu]
    cpuset: "12-15"
    restart: "no"
    runtime: "nvidia"
    networks:
      - default
