version: '3'

networks:
  default:
    name: ollama-network
    external: true

services:
  lusha_req_manager:
    environment:
      - OLLAMA_URL=http://lusha_ollama:11434
      - PYTHONUNBUFFERED=1
    build: .
    container_name: phi3_gen
    user: "${UID}:${GID}"
    
    deploy:
      resources:
        reservations:
          devices:
            - capabilities: [gpu]
              count: 0
    volumes:
      - /home/lusha/storage/star_code/outputs:/app/outputs
      - /home/lusha/storage/star_code/data:/app/data
      - /home/lusha/datasets/private:/app/data/datasets
      - /home/lusha/storage/star_code/src:/app/src
    cpuset: "12-15"
    networks:
      - default
