version: '3'

networks:
  default:
    name: lusha_network
    external: true

services:
  lusha_llama8b_judge:
    environment:
      - OLLAMA_URL=http://lusha_ollama:11434
      - PYTHONUNBUFFERED=1
    stdin_open: true  # Keep stdin open
    tty: true        # Allocate a pseudo-TTY
    build: .
    container_name: lusha_req_mng
    user: "${UID-1142}:${GID-1142}"
    
    deploy:
      resources:
        reservations:
          devices:
            - capabilities: [gpu]
              count: 0
    volumes:
      - /home/lusha/storage/star_code/outputs:/app/outputs
      - /home/lusha/storage/star_code/data:/app/data
      - /home/lusha/datasets/private:/app/data/datasets
      - /home/lusha/storage/star_code/src:/app/src
    cpuset: "12-15"
    networks:
      - default
