version: '3'
networks:
  default:
    name: lusha_net

services:
  ollama_service:
    image: lusha/ollama
    environment:
      - OLLAMA_HOST=0.0.0.0:11435
      - OLLAMA_LOG=debug
      - OLLAMA_DEBUG=1
      - OLLAMA_NUM_PARALLEL=2
    user: "${UID-1142}:${GID-1142}"
    ports:  
      - "11435:11435"
    volumes:
      - /home/lusha/storage/ollama/ollama_models:/.ollama 
    container_name: lusha_ollama
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              device_ids: ["4"]
              capabilities: [gpu]
    cpuset: "0-7"
    restart: "no"
    runtime: "nvidia"
    networks:
      - default

  ollama_service2:
    image: lusha/ollama
    environment:
      - OLLAMA_HOST=0.0.0.0:11434
      - OLLAMA_LOG=debug
      - OLLAMA_DEBUG=1
      - OLLAMA_NUM_PARALLEL=4
    user: "${UID-1142}:${GID-1142}"
    ports:  
      - "11434:11434"
    volumes:
      - /home/lusha/storage/ollama/ollama_models:/.ollama 
    container_name: lusha_ollama2
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              device_ids: ["4"]
              capabilities: [gpu]
    cpuset: "0-7"
    restart: "no"
    runtime: "nvidia"
    networks:
      - default
