networks:
  default:
    name: ${USER}_ollama_net

services:
  ollama_service:
    image: ollama/ollama:0.9.1
    environment:
      - OLLAMA_HOST=0.0.0.0:11435
      - OLLAMA_LOG=debug
      - OLLAMA_DEBUG=1
      - OLLAMA_NUM_PARALLEL=2
    user: "${UID-1142}:${GID-1142}"
    ports:  
      - "11435:11435"
    volumes:
      - /multiverse/datasets/shared/ollama_models:/.ollama
    container_name: ${USER}_ollama
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              device_ids: ["2"]
              capabilities: [gpu]
    cpuset: "12-19"
    restart: "no"
    runtime: "nvidia"
    networks:
      - default
