version: '3'
services:
  ollama:
    image: lusha/ollama
    user: "${UID}:${GID}"
    working_dir: /home/lusha
    ports:
      - "11434:11434"
    volumes:
      - /home/lusha/storage/ollama/ollama_models:/.ollama
    container_name: ollama
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              device_ids: ['4']
              capabilities: [gpu]
    cpuset: "32-35"
    restart: "no"