version: '3'

networks:
  default:
    name: ollama-network
    external: true

services:
  ollama:
    image: lusha/ollama
    user: "${UID}:${GID}"
    working_dir: /home/lusha
    ports:
      - "11434:11434"
    volumes:
      - /home/lusha/storage/ollama/ollama_models:/.ollama
    container_name: ollama
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              device_ids: ['0']
              capabilities: [gpu]
    cpuset: "12-15"
    networks:
      - default
    restart: "no"
