networks:
  default:
    name: ${USER}_ollama_net

services:
  env_container:
    image: lusha/pydev
    container_name: ${USER}_pydev_env
    env_file:
      - .env
      - private.env
    user: "${USER}:${USER}"
    stdin_open: true  # same as -i
    tty: true         # same as -t
    command: /bin/bash
    ports: # HOST:CONTAINER
      - "10882:8888"
    volumes:
      - ../:/home/${USER}
      - ../star_code/data/datasets:/home/${USER}/star_code/data/datasets
      - /multiverse/datasets/shared/action-genome:/home/${USER}/star_code/data/datasets/action-genome
      - /multiverse/datasets/shared/action-genome/Charades_v1_480:/home/${USER}/star_code/data/datasets/action-genome/Charades_v1_480
      - /multiverse/datasets/shared/STAR:/home/${USER}/star_code/data/datasets/STAR
    deploy:
      resources:
        reservations:
          devices:
            - capabilities: [gpu]
              device_ids: ["3"]
    cpuset: "0-7"
